package com.example.erp.wenwei.pojo;

import java.util.Date;

public class AllottEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4189374439699797122L;

    /* This code was generated by TableGo tools, mark 1 begin. */


    private Integer wareoutid;

    private Integer wareinid;

    private Integer permitter;

    private String moveDate;

    private String moveno;


    private Integer makerid;

    private String movedetailno;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取wareoutid
     * 
     * @return wareoutid
     */
    public Integer getWareoutid() {
        return this.wareoutid;
    }

    /**
     * 设置wareoutid
     * 
     * @param wareoutid
     */
    public void setWareoutid(Integer wareoutid) {
        this.wareoutid = wareoutid;
    }

    /**
     * 获取wareinid
     * 
     * @return wareinid
     */
    public Integer getWareinid() {
        return this.wareinid;
    }

    /**
     * 设置wareinid
     * 
     * @param wareinid
     */
    public void setWareinid(Integer wareinid) {
        this.wareinid = wareinid;
    }

    /**
     * 获取permitter
     * 
     * @return permitter
     */
    public Integer getPermitter() {
        return this.permitter;
    }

    /**
     * 设置permitter
     * 
     * @param permitter
     */
    public void setPermitter(Integer permitter) {
        this.permitter = permitter;
    }

    /**
     * 获取moveDate
     * 
     * @return moveDate
     */
    public String getMoveDate() {
        return this.moveDate;
    }

    /**
     * 设置moveDate
     * 
     * @param moveDate
     */
    public void setMoveDate(String moveDate) {
        this.moveDate = moveDate;
    }

    /**
     * 获取moveno
     * 
     * @return moveno
     */
    public String getMoveno() {
        return this.moveno;
    }

    /**
     * 设置moveno
     * 
     * @param moveno
     */
    public void setMoveno(String moveno) {
        this.moveno = moveno;
    }

    /**
     * 获取makerid
     * 
     * @return makerid
     */
    public Integer getMakerid() {
        return this.makerid;
    }

    /**
     * 设置makerid
     * 
     * @param makerid
     */
    public void setMakerid(Integer makerid) {
        this.makerid = makerid;
    }

    /**
     * 获取movedetailno
     * 
     * @return movedetailno
     */
    public String getMovedetailno() {
        return this.movedetailno;
    }

    /**
     * 设置movedetailno
     * 
     * @param movedetailno
     */
    public void setMovedetailno(String movedetailno) {
        this.movedetailno = movedetailno;
    }

	@Override
	public String toString() {
		return "AllottEntity [wareoutid=" + wareoutid + ", wareinid=" + wareinid + ", permitter=" + permitter
				+ ", moveDate=" + moveDate + ", moveno=" + moveno + ", makerid=" + makerid + ", movedetailno="
				+ movedetailno + "]";
	}

	public AllottEntity(Integer wareoutid, Integer wareinid, Integer permitter, String moveDate, String moveno,
			Integer makerid, String movedetailno) {
		super();
		this.wareoutid = wareoutid;
		this.wareinid = wareinid;
		this.permitter = permitter;
		this.moveDate = moveDate;
		this.moveno = moveno;
		this.makerid = makerid;
		this.movedetailno = movedetailno;
	}
    
    
    /* This code was generated by TableGo tools, mark 2 end. */
}