package com.example.erp.wenwei.pojo;
public class ChangedetailEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -8353131871318797662L;

    /* This code was generated by TableGo tools, mark 1 begin. */


    private String checkbillno3;


    private String prodid;


    private String reason;


    private String changedetailno;


    private String changeBillNo;


    private Integer changeNumber;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取checkbillno3
     * 
     * @return checkbillno3
     */
    public String getCheckbillno3() {
        return this.checkbillno3;
    }

    /**
     * 设置checkbillno3
     * 
     * @param checkbillno3
     */
    public void setCheckbillno3(String checkbillno3) {
        this.checkbillno3 = checkbillno3;
    }

    /**
     * 获取prodid
     * 
     * @return prodid
     */
    public String getProdid() {
        return this.prodid;
    }

    /**
     * 设置prodid
     * 
     * @param prodid
     */
    public void setProdid(String prodid) {
        this.prodid = prodid;
    }

    /**
     * 获取reason
     * 
     * @return reason
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * 设置reason
     * 
     * @param reason
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * 获取changedetailno
     * 
     * @return changedetailno
     */
    public String getChangedetailno() {
        return this.changedetailno;
    }

    /**
     * 设置changedetailno
     * 
     * @param changedetailno
     */
    public void setChangedetailno(String changedetailno) {
        this.changedetailno = changedetailno;
    }

    /**
     * 获取changeBillNo
     * 
     * @return changeBillNo
     */
    public String getChangeBillNo() {
        return this.changeBillNo;
    }

    /**
     * 设置changeBillNo
     * 
     * @param changeBillNo
     */
    public void setChangeBillNo(String changeBillNo) {
        this.changeBillNo = changeBillNo;
    }

    /**
     * 获取changeNumber
     * 
     * @return changeNumber
     */
    public Integer getChangeNumber() {
        return this.changeNumber;
    }

    /**
     * 设置changeNumber
     * 
     * @param changeNumber
     */
    public void setChangeNumber(Integer changeNumber) {
        this.changeNumber = changeNumber;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}