package com.example.erp.wenwei.pojo;

import java.util.Date;

public class CheckwarehouseEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -337673060530728301L;

    /* This code was generated by TableGo tools, mark 1 begin. */

<<<<<<< HEAD

    private Integer checkwareid;


    private String incsubjectid;


    private String decsubjectid;


    private Date adjustDate;

    /** checkbillno */

    private String checkbillno;

    
    private String voucherno;

   
    private String waredetailsno;

  
    private Integer saleid;


    private Integer departid;


    private Integer makerid;

 
=======

    private Integer checkwareid;


    private String incsubjectid;


    private String decsubjectid;


    private Date adjustDate;

    /** checkbillno */

    private String checkbillno;

    
    private String voucherno;

   
    private String waredetailsno;

  
    private Integer saleid;


    private Integer departid;


    private Integer makerid;

 
>>>>>>> parent of feee0d9... s
    private Integer permitterid;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取checkwareid
     * 
     * @return checkwareid
     */
    public Integer getCheckwareid() {
        return this.checkwareid;
    }

    /**
     * 设置checkwareid
     * 
     * @param checkwareid
     */
    public void setCheckwareid(Integer checkwareid) {
        this.checkwareid = checkwareid;
    }

    /**
     * 获取incsubjectid
     * 
     * @return incsubjectid
     */
    public String getIncsubjectid() {
        return this.incsubjectid;
    }

    /**
     * 设置incsubjectid
     * 
     * @param incsubjectid
     */
    public void setIncsubjectid(String incsubjectid) {
        this.incsubjectid = incsubjectid;
    }

    /**
     * 获取decsubjectid
     * 
     * @return decsubjectid
     */
    public String getDecsubjectid() {
        return this.decsubjectid;
    }

    /**
     * 设置decsubjectid
     * 
     * @param decsubjectid
     */
    public void setDecsubjectid(String decsubjectid) {
        this.decsubjectid = decsubjectid;
    }

    /**
     * 获取adjustDate
     * 
     * @return adjustDate
     */
    public Date getAdjustDate() {
        return this.adjustDate;
    }

    /**
     * 设置adjustDate
     * 
     * @param adjustDate
     */
    public void setAdjustDate(Date adjustDate) {
        this.adjustDate = adjustDate;
    }

    /**
     * 获取checkbillno
     * 
     * @return checkbillno
     */
    public String getCheckbillno() {
        return this.checkbillno;
    }

    /**
     * 设置checkbillno
     * 
     * @param checkbillno
     */
    public void setCheckbillno(String checkbillno) {
        this.checkbillno = checkbillno;
    }

    /**
     * 获取voucherno
     * 
     * @return voucherno
     */
    public String getVoucherno() {
        return this.voucherno;
    }

    /**
     * 设置voucherno
     * 
     * @param voucherno
     */
    public void setVoucherno(String voucherno) {
        this.voucherno = voucherno;
    }

    /**
     * 获取waredetailsno
     * 
     * @return waredetailsno
     */
    public String getWaredetailsno() {
        return this.waredetailsno;
    }

    /**
     * 设置waredetailsno
     * 
     * @param waredetailsno
     */
    public void setWaredetailsno(String waredetailsno) {
        this.waredetailsno = waredetailsno;
    }

    /**
     * 获取saleid
     * 
     * @return saleid
     */
    public Integer getSaleid() {
        return this.saleid;
    }

    /**
     * 设置saleid
     * 
     * @param saleid
     */
    public void setSaleid(Integer saleid) {
        this.saleid = saleid;
    }

    /**
     * 获取departid
     * 
     * @return departid
     */
    public Integer getDepartid() {
        return this.departid;
    }

    /**
     * 设置departid
     * 
     * @param departid
     */
    public void setDepartid(Integer departid) {
        this.departid = departid;
    }

    /**
     * 获取makerid
     * 
     * @return makerid
     */
    public Integer getMakerid() {
        return this.makerid;
    }

    /**
     * 设置makerid
     * 
     * @param makerid
     */
    public void setMakerid(Integer makerid) {
        this.makerid = makerid;
    }

    /**
     * 获取permitterid
     * 
     * @return permitterid
     */
    public Integer getPermitterid() {
        return this.permitterid;
    }

    /**
     * 设置permitterid
     * 
     * @param permitterid
     */
    public void setPermitterid(Integer permitterid) {
        this.permitterid = permitterid;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}