package com.example.erp.wenwei.pojo;

import java.util.Date;

public class DsproductprodidEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7962364081954525915L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 物料编号 */
    private String prodid;

    /** 物料类别 */
    private String classid;

    /** 类别名称 */
    private String classname;

    /** 条形码编号 */
    private String barcodeid;

    /** 物料名称 */
    private String prodname;

    /** 规格型号 */
    private String prodsizi;

    /** 英文品名 */
    private String engname;

    /** 使用币别 */
    private String currid;

    /** 币别名称 */
    private String currname;

    /** 建议售价 */
    private String suggestprice;

    /** 售价A */
    private String salespricea;

    /** 售价B */
    private String salespriceb;

    /** 售价C */
    private String salespricec;

    /** 售价D */
    private String salespriced;

    /** 售价E */
    private String salespricee;

    /** 标准进价 */
    private String stdprice;

    /** 税率 */
    private String busitaxrate;

    /** 使用批号管理 */
    private String batchused;

    /** 使用出厂日期 */
    private Date effectdateused;

    /** 使用有效日期 */
    private Date validdateused;

    /** 有效天数 */
    private String defvalidday;

    /** 物料说明 */
    private String proddesc;

    /** 物料形态 */
    private String prodform;

    /** 采购提前期 */
    private String advancedays;

    /** 主供应商 */
    private String majorsupplier;

    /** 供应商名称 */
    private String majorsuppliername;

    /** 最初出库日 */
    private Date boutstockday;

    /** 最初入库日 */
    private Date binstockday;

    /** 呆滞起记天数 */
    private String sluggishdays;

    /** 停用日期 */
    private Date invaliddate;

    /** 安全存量 */
    private String safeqty;

    /** 20CY */
    private String cy20;

    /** 40CY */
    private String cy40;

    /** 40HQ */
    private String hq40;

    /** 45CY */
    private String cy45;

    /** 内包装容量 */
    private String inpackamt;

    /** 外包装容量 */
    private String outpackamt;

    /** 材积单位 */
    private String volumeunit;

    /** Measm’t */
    private String volume;

    /** N.W */
    private String netweight;

    /** G.W */
    private String grossweigh;

    /** 标准成本 */
    private String bstdcost;

    /** 平均成本 */
    private String bavgcost;

    /** 现行平均成本 */
    private String cavgcost;

    /** 物料总成本 */
    private String ctotalcost;

    /** 自定义栏一 */
    private String udef1;

    /** 自定义栏二 */
    private String udef2;

    /** 单价是否含税 */
    private String priceoftax;

    /** 期初总成本 */
    private String btotalcost;

    /** 计量单位 */
    private String stdunitid;

    /** 单位名称 */
    private String stdunitname;

    /** 英文单位 */
    private String stdunitengname;

    /** 现有总数量 */
    private String callamt;

    /** 单位净重 */
    private String nweight;

    /** 包装物重量 */
    private String gweight;

    /** 长 */
    private String Long;

    /** 长度单位 */
    private String lunit;

    /** 宽 */
    private String width;

    /** 高 */
    private String higth;

    /** Measm’t */
    private String mvolume;

    /** 产品打雷 */
    private String probigtype;

    /** 退税率% */
    private String backtaxrate;

    /** 税目 */
    private String taxitemsid;

    /** 期初总数量 */
    private String ballamt;

    /** 实际在库存 */
    private String bcurrstock;

    /** 安全总存量 */
    private String bsafeallstk;

    /** 低于安全存量 */
    private String csafeallstk;

    /** 实际在库量 */
    private String ccurrstock;

    /** 标准总成本 */
    private String cstdcost;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取物料编号
     * 
     * @return 物料编号
     */
    public String getProdid() {
        return this.prodid;
    }

    /**
     * 设置物料编号
     * 
     * @param prodid
     *          物料编号
     */
    public void setProdid(String prodid) {
        this.prodid = prodid;
    }

    /**
     * 获取物料类别
     * 
     * @return 物料类别
     */
    public String getClassid() {
        return this.classid;
    }

    /**
     * 设置物料类别
     * 
     * @param classid
     *          物料类别
     */
    public void setClassid(String classid) {
        this.classid = classid;
    }

    /**
     * 获取类别名称
     * 
     * @return 类别名称
     */
    public String getClassname() {
        return this.classname;
    }

    /**
     * 设置类别名称
     * 
     * @param classname
     *          类别名称
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * 获取条形码编号
     * 
     * @return 条形码编号
     */
    public String getBarcodeid() {
        return this.barcodeid;
    }

    /**
     * 设置条形码编号
     * 
     * @param barcodeid
     *          条形码编号
     */
    public void setBarcodeid(String barcodeid) {
        this.barcodeid = barcodeid;
    }

    /**
     * 获取物料名称
     * 
     * @return 物料名称
     */
    public String getProdname() {
        return this.prodname;
    }

    /**
     * 设置物料名称
     * 
     * @param prodname
     *          物料名称
     */
    public void setProdname(String prodname) {
        this.prodname = prodname;
    }

    /**
     * 获取规格型号
     * 
     * @return 规格型号
     */
    public String getProdsizi() {
        return this.prodsizi;
    }

    /**
     * 设置规格型号
     * 
     * @param prodsizi
     *          规格型号
     */
    public void setProdsizi(String prodsizi) {
        this.prodsizi = prodsizi;
    }

    /**
     * 获取英文品名
     * 
     * @return 英文品名
     */
    public String getEngname() {
        return this.engname;
    }

    /**
     * 设置英文品名
     * 
     * @param engname
     *          英文品名
     */
    public void setEngname(String engname) {
        this.engname = engname;
    }

    /**
     * 获取使用币别
     * 
     * @return 使用币别
     */
    public String getCurrid() {
        return this.currid;
    }

    /**
     * 设置使用币别
     * 
     * @param currid
     *          使用币别
     */
    public void setCurrid(String currid) {
        this.currid = currid;
    }

    /**
     * 获取币别名称
     * 
     * @return 币别名称
     */
    public String getCurrname() {
        return this.currname;
    }

    /**
     * 设置币别名称
     * 
     * @param currname
     *          币别名称
     */
    public void setCurrname(String currname) {
        this.currname = currname;
    }

    /**
     * 获取建议售价
     * 
     * @return 建议售价
     */
    public String getSuggestprice() {
        return this.suggestprice;
    }

    /**
     * 设置建议售价
     * 
     * @param suggestprice
     *          建议售价
     */
    public void setSuggestprice(String suggestprice) {
        this.suggestprice = suggestprice;
    }

    /**
     * 获取售价A
     * 
     * @return 售价A
     */
    public String getSalespricea() {
        return this.salespricea;
    }

    /**
     * 设置售价A
     * 
     * @param salespricea
     *          售价A
     */
    public void setSalespricea(String salespricea) {
        this.salespricea = salespricea;
    }

    /**
     * 获取售价B
     * 
     * @return 售价B
     */
    public String getSalespriceb() {
        return this.salespriceb;
    }

    /**
     * 设置售价B
     * 
     * @param salespriceb
     *          售价B
     */
    public void setSalespriceb(String salespriceb) {
        this.salespriceb = salespriceb;
    }

    /**
     * 获取售价C
     * 
     * @return 售价C
     */
    public String getSalespricec() {
        return this.salespricec;
    }

    /**
     * 设置售价C
     * 
     * @param salespricec
     *          售价C
     */
    public void setSalespricec(String salespricec) {
        this.salespricec = salespricec;
    }

    /**
     * 获取售价D
     * 
     * @return 售价D
     */
    public String getSalespriced() {
        return this.salespriced;
    }

    /**
     * 设置售价D
     * 
     * @param salespriced
     *          售价D
     */
    public void setSalespriced(String salespriced) {
        this.salespriced = salespriced;
    }

    /**
     * 获取售价E
     * 
     * @return 售价E
     */
    public String getSalespricee() {
        return this.salespricee;
    }

    /**
     * 设置售价E
     * 
     * @param salespricee
     *          售价E
     */
    public void setSalespricee(String salespricee) {
        this.salespricee = salespricee;
    }

    /**
     * 获取标准进价
     * 
     * @return 标准进价
     */
    public String getStdprice() {
        return this.stdprice;
    }

    /**
     * 设置标准进价
     * 
     * @param stdprice
     *          标准进价
     */
    public void setStdprice(String stdprice) {
        this.stdprice = stdprice;
    }

    /**
     * 获取税率
     * 
     * @return 税率
     */
    public String getBusitaxrate() {
        return this.busitaxrate;
    }

    /**
     * 设置税率
     * 
     * @param busitaxrate
     *          税率
     */
    public void setBusitaxrate(String busitaxrate) {
        this.busitaxrate = busitaxrate;
    }

    /**
     * 获取使用批号管理
     * 
     * @return 使用批号管理
     */
    public String getBatchused() {
        return this.batchused;
    }

    /**
     * 设置使用批号管理
     * 
     * @param batchused
     *          使用批号管理
     */
    public void setBatchused(String batchused) {
        this.batchused = batchused;
    }

    /**
     * 获取使用出厂日期
     * 
     * @return 使用出厂日期
     */
    public Date getEffectdateused() {
        return this.effectdateused;
    }

    /**
     * 设置使用出厂日期
     * 
     * @param effectdateused
     *          使用出厂日期
     */
    public void setEffectdateused(Date effectdateused) {
        this.effectdateused = effectdateused;
    }

    /**
     * 获取使用有效日期
     * 
     * @return 使用有效日期
     */
    public Date getValiddateused() {
        return this.validdateused;
    }

    /**
     * 设置使用有效日期
     * 
     * @param validdateused
     *          使用有效日期
     */
    public void setValiddateused(Date validdateused) {
        this.validdateused = validdateused;
    }

    /**
     * 获取有效天数
     * 
     * @return 有效天数
     */
    public String getDefvalidday() {
        return this.defvalidday;
    }

    /**
     * 设置有效天数
     * 
     * @param defvalidday
     *          有效天数
     */
    public void setDefvalidday(String defvalidday) {
        this.defvalidday = defvalidday;
    }

    /**
     * 获取物料说明
     * 
     * @return 物料说明
     */
    public String getProddesc() {
        return this.proddesc;
    }

    /**
     * 设置物料说明
     * 
     * @param proddesc
     *          物料说明
     */
    public void setProddesc(String proddesc) {
        this.proddesc = proddesc;
    }

    /**
     * 获取物料形态
     * 
     * @return 物料形态
     */
    public String getProdform() {
        return this.prodform;
    }

    /**
     * 设置物料形态
     * 
     * @param prodform
     *          物料形态
     */
    public void setProdform(String prodform) {
        this.prodform = prodform;
    }

    /**
     * 获取采购提前期
     * 
     * @return 采购提前期
     */
    public String getAdvancedays() {
        return this.advancedays;
    }

    /**
     * 设置采购提前期
     * 
     * @param advancedays
     *          采购提前期
     */
    public void setAdvancedays(String advancedays) {
        this.advancedays = advancedays;
    }

    /**
     * 获取主供应商
     * 
     * @return 主供应商
     */
    public String getMajorsupplier() {
        return this.majorsupplier;
    }

    /**
     * 设置主供应商
     * 
     * @param majorsupplier
     *          主供应商
     */
    public void setMajorsupplier(String majorsupplier) {
        this.majorsupplier = majorsupplier;
    }

    /**
     * 获取供应商名称
     * 
     * @return 供应商名称
     */
    public String getMajorsuppliername() {
        return this.majorsuppliername;
    }

    /**
     * 设置供应商名称
     * 
     * @param majorsuppliername
     *          供应商名称
     */
    public void setMajorsuppliername(String majorsuppliername) {
        this.majorsuppliername = majorsuppliername;
    }

    /**
     * 获取最初出库日
     * 
     * @return 最初出库日
     */
    public Date getBoutstockday() {
        return this.boutstockday;
    }

    /**
     * 设置最初出库日
     * 
     * @param boutstockday
     *          最初出库日
     */
    public void setBoutstockday(Date boutstockday) {
        this.boutstockday = boutstockday;
    }

    /**
     * 获取最初入库日
     * 
     * @return 最初入库日
     */
    public Date getBinstockday() {
        return this.binstockday;
    }

    /**
     * 设置最初入库日
     * 
     * @param binstockday
     *          最初入库日
     */
    public void setBinstockday(Date binstockday) {
        this.binstockday = binstockday;
    }

    /**
     * 获取呆滞起记天数
     * 
     * @return 呆滞起记天数
     */
    public String getSluggishdays() {
        return this.sluggishdays;
    }

    /**
     * 设置呆滞起记天数
     * 
     * @param sluggishdays
     *          呆滞起记天数
     */
    public void setSluggishdays(String sluggishdays) {
        this.sluggishdays = sluggishdays;
    }

    /**
     * 获取停用日期
     * 
     * @return 停用日期
     */
    public Date getInvaliddate() {
        return this.invaliddate;
    }

    /**
     * 设置停用日期
     * 
     * @param invaliddate
     *          停用日期
     */
    public void setInvaliddate(Date invaliddate) {
        this.invaliddate = invaliddate;
    }

    /**
     * 获取安全存量
     * 
     * @return 安全存量
     */
    public String getSafeqty() {
        return this.safeqty;
    }

    /**
     * 设置安全存量
     * 
     * @param safeqty
     *          安全存量
     */
    public void setSafeqty(String safeqty) {
        this.safeqty = safeqty;
    }

    /**
     * 获取20CY
     * 
     * @return 20CY
     */
    public String getCy20() {
        return this.cy20;
    }

    /**
     * 设置20CY
     * 
     * @param cy20
     *          20CY
     */
    public void setCy20(String cy20) {
        this.cy20 = cy20;
    }

    /**
     * 获取40CY
     * 
     * @return 40CY
     */
    public String getCy40() {
        return this.cy40;
    }

    /**
     * 设置40CY
     * 
     * @param cy40
     *          40CY
     */
    public void setCy40(String cy40) {
        this.cy40 = cy40;
    }

    /**
     * 获取40HQ
     * 
     * @return 40HQ
     */
    public String getHq40() {
        return this.hq40;
    }

    /**
     * 设置40HQ
     * 
     * @param hq40
     *          40HQ
     */
    public void setHq40(String hq40) {
        this.hq40 = hq40;
    }

    /**
     * 获取45CY
     * 
     * @return 45CY
     */
    public String getCy45() {
        return this.cy45;
    }

    /**
     * 设置45CY
     * 
     * @param cy45
     *          45CY
     */
    public void setCy45(String cy45) {
        this.cy45 = cy45;
    }

    /**
     * 获取内包装容量
     * 
     * @return 内包装容量
     */
    public String getInpackamt() {
        return this.inpackamt;
    }

    /**
     * 设置内包装容量
     * 
     * @param inpackamt
     *          内包装容量
     */
    public void setInpackamt(String inpackamt) {
        this.inpackamt = inpackamt;
    }

    /**
     * 获取外包装容量
     * 
     * @return 外包装容量
     */
    public String getOutpackamt() {
        return this.outpackamt;
    }

    /**
     * 设置外包装容量
     * 
     * @param outpackamt
     *          外包装容量
     */
    public void setOutpackamt(String outpackamt) {
        this.outpackamt = outpackamt;
    }

    /**
     * 获取材积单位
     * 
     * @return 材积单位
     */
    public String getVolumeunit() {
        return this.volumeunit;
    }

    /**
     * 设置材积单位
     * 
     * @param volumeunit
     *          材积单位
     */
    public void setVolumeunit(String volumeunit) {
        this.volumeunit = volumeunit;
    }

    /**
     * 获取Measm’t
     * 
     * @return Measm’t
     */
    public String getVolume() {
        return this.volume;
    }

    /**
     * 设置Measm’t
     * 
     * @param volume
     *          Measm’t
     */
    public void setVolume(String volume) {
        this.volume = volume;
    }

    /**
     * 获取N.W
     * 
     * @return N.W
     */
    public String getNetweight() {
        return this.netweight;
    }

    /**
     * 设置N.W
     * 
     * @param netweight
     *          N.W
     */
    public void setNetweight(String netweight) {
        this.netweight = netweight;
    }

    /**
     * 获取G.W
     * 
     * @return G.W
     */
    public String getGrossweigh() {
        return this.grossweigh;
    }

    /**
     * 设置G.W
     * 
     * @param grossweigh
     *          G.W
     */
    public void setGrossweigh(String grossweigh) {
        this.grossweigh = grossweigh;
    }

    /**
     * 获取标准成本
     * 
     * @return 标准成本
     */
    public String getBstdcost() {
        return this.bstdcost;
    }

    /**
     * 设置标准成本
     * 
     * @param bstdcost
     *          标准成本
     */
    public void setBstdcost(String bstdcost) {
        this.bstdcost = bstdcost;
    }

    /**
     * 获取平均成本
     * 
     * @return 平均成本
     */
    public String getBavgcost() {
        return this.bavgcost;
    }

    /**
     * 设置平均成本
     * 
     * @param bavgcost
     *          平均成本
     */
    public void setBavgcost(String bavgcost) {
        this.bavgcost = bavgcost;
    }

    /**
     * 获取现行平均成本
     * 
     * @return 现行平均成本
     */
    public String getCavgcost() {
        return this.cavgcost;
    }

    /**
     * 设置现行平均成本
     * 
     * @param cavgcost
     *          现行平均成本
     */
    public void setCavgcost(String cavgcost) {
        this.cavgcost = cavgcost;
    }

    /**
     * 获取物料总成本
     * 
     * @return 物料总成本
     */
    public String getCtotalcost() {
        return this.ctotalcost;
    }

    /**
     * 设置物料总成本
     * 
     * @param ctotalcost
     *          物料总成本
     */
    public void setCtotalcost(String ctotalcost) {
        this.ctotalcost = ctotalcost;
    }

    /**
     * 获取自定义栏一
     * 
     * @return 自定义栏一
     */
    public String getUdef1() {
        return this.udef1;
    }

    /**
     * 设置自定义栏一
     * 
     * @param udef1
     *          自定义栏一
     */
    public void setUdef1(String udef1) {
        this.udef1 = udef1;
    }

    /**
     * 获取自定义栏二
     * 
     * @return 自定义栏二
     */
    public String getUdef2() {
        return this.udef2;
    }

    /**
     * 设置自定义栏二
     * 
     * @param udef2
     *          自定义栏二
     */
    public void setUdef2(String udef2) {
        this.udef2 = udef2;
    }

    /**
     * 获取单价是否含税
     * 
     * @return 单价是否含税
     */
    public String getPriceoftax() {
        return this.priceoftax;
    }

    /**
     * 设置单价是否含税
     * 
     * @param priceoftax
     *          单价是否含税
     */
    public void setPriceoftax(String priceoftax) {
        this.priceoftax = priceoftax;
    }

    /**
     * 获取期初总成本
     * 
     * @return 期初总成本
     */
    public String getBtotalcost() {
        return this.btotalcost;
    }

    /**
     * 设置期初总成本
     * 
     * @param btotalcost
     *          期初总成本
     */
    public void setBtotalcost(String btotalcost) {
        this.btotalcost = btotalcost;
    }

    /**
     * 获取计量单位
     * 
     * @return 计量单位
     */
    public String getStdunitid() {
        return this.stdunitid;
    }

    /**
     * 设置计量单位
     * 
     * @param stdunitid
     *          计量单位
     */
    public void setStdunitid(String stdunitid) {
        this.stdunitid = stdunitid;
    }

    /**
     * 获取单位名称
     * 
     * @return 单位名称
     */
    public String getStdunitname() {
        return this.stdunitname;
    }

    /**
     * 设置单位名称
     * 
     * @param stdunitname
     *          单位名称
     */
    public void setStdunitname(String stdunitname) {
        this.stdunitname = stdunitname;
    }

    /**
     * 获取英文单位
     * 
     * @return 英文单位
     */
    public String getStdunitengname() {
        return this.stdunitengname;
    }

    /**
     * 设置英文单位
     * 
     * @param stdunitengname
     *          英文单位
     */
    public void setStdunitengname(String stdunitengname) {
        this.stdunitengname = stdunitengname;
    }

    /**
     * 获取现有总数量
     * 
     * @return 现有总数量
     */
    public String getCallamt() {
        return this.callamt;
    }

    /**
     * 设置现有总数量
     * 
     * @param callamt
     *          现有总数量
     */
    public void setCallamt(String callamt) {
        this.callamt = callamt;
    }

    /**
     * 获取单位净重
     * 
     * @return 单位净重
     */
    public String getNweight() {
        return this.nweight;
    }

    /**
     * 设置单位净重
     * 
     * @param nweight
     *          单位净重
     */
    public void setNweight(String nweight) {
        this.nweight = nweight;
    }

    /**
     * 获取包装物重量
     * 
     * @return 包装物重量
     */
    public String getGweight() {
        return this.gweight;
    }

    /**
     * 设置包装物重量
     * 
     * @param gweight
     *          包装物重量
     */
    public void setGweight(String gweight) {
        this.gweight = gweight;
    }

    /**
     * 获取长
     * 
     * @return 长
     */
    public String getLong() {
        return this.Long;
    }

    /**
     * 设置长
     * 
     * @param long
     *          长
     */
    public void setLong(String Long) {
        this.Long = Long;
    }

    /**
     * 获取长度单位
     * 
     * @return 长度单位
     */
    public String getLunit() {
        return this.lunit;
    }

    /**
     * 设置长度单位
     * 
     * @param lunit
     *          长度单位
     */
    public void setLunit(String lunit) {
        this.lunit = lunit;
    }

    /**
     * 获取宽
     * 
     * @return 宽
     */
    public String getWidth() {
        return this.width;
    }

    /**
     * 设置宽
     * 
     * @param width
     *          宽
     */
    public void setWidth(String width) {
        this.width = width;
    }

    /**
     * 获取高
     * 
     * @return 高
     */
    public String getHigth() {
        return this.higth;
    }

    /**
     * 设置高
     * 
     * @param higth
     *          高
     */
    public void setHigth(String higth) {
        this.higth = higth;
    }

    /**
     * 获取Measm’t
     * 
     * @return Measm’t
     */
    public String getMvolume() {
        return this.mvolume;
    }

    /**
     * 设置Measm’t
     * 
     * @param mvolume
     *          Measm’t
     */
    public void setMvolume(String mvolume) {
        this.mvolume = mvolume;
    }

    /**
     * 获取产品打雷
     * 
     * @return 产品打雷
     */
    public String getProbigtype() {
        return this.probigtype;
    }

    /**
     * 设置产品打雷
     * 
     * @param probigtype
     *          产品打雷
     */
    public void setProbigtype(String probigtype) {
        this.probigtype = probigtype;
    }

    /**
     * 获取退税率%
     * 
     * @return 退税率%
     */
    public String getBacktaxrate() {
        return this.backtaxrate;
    }

    /**
     * 设置退税率%
     * 
     * @param backtaxrate
     *          退税率%
     */
    public void setBacktaxrate(String backtaxrate) {
        this.backtaxrate = backtaxrate;
    }

    /**
     * 获取税目
     * 
     * @return 税目
     */
    public String getTaxitemsid() {
        return this.taxitemsid;
    }

    /**
     * 设置税目
     * 
     * @param taxitemsid
     *          税目
     */
    public void setTaxitemsid(String taxitemsid) {
        this.taxitemsid = taxitemsid;
    }

    /**
     * 获取期初总数量
     * 
     * @return 期初总数量
     */
    public String getBallamt() {
        return this.ballamt;
    }

    /**
     * 设置期初总数量
     * 
     * @param ballamt
     *          期初总数量
     */
    public void setBallamt(String ballamt) {
        this.ballamt = ballamt;
    }

    /**
     * 获取实际在库存
     * 
     * @return 实际在库存
     */
    public String getBcurrstock() {
        return this.bcurrstock;
    }

    /**
     * 设置实际在库存
     * 
     * @param bcurrstock
     *          实际在库存
     */
    public void setBcurrstock(String bcurrstock) {
        this.bcurrstock = bcurrstock;
    }

    /**
     * 获取安全总存量
     * 
     * @return 安全总存量
     */
    public String getBsafeallstk() {
        return this.bsafeallstk;
    }

    /**
     * 设置安全总存量
     * 
     * @param bsafeallstk
     *          安全总存量
     */
    public void setBsafeallstk(String bsafeallstk) {
        this.bsafeallstk = bsafeallstk;
    }

    /**
     * 获取低于安全存量
     * 
     * @return 低于安全存量
     */
    public String getCsafeallstk() {
        return this.csafeallstk;
    }

    /**
     * 设置低于安全存量
     * 
     * @param csafeallstk
     *          低于安全存量
     */
    public void setCsafeallstk(String csafeallstk) {
        this.csafeallstk = csafeallstk;
    }

    /**
     * 获取实际在库量
     * 
     * @return 实际在库量
     */
    public String getCcurrstock() {
        return this.ccurrstock;
    }

    /**
     * 设置实际在库量
     * 
     * @param ccurrstock
     *          实际在库量
     */
    public void setCcurrstock(String ccurrstock) {
        this.ccurrstock = ccurrstock;
    }

    /**
     * 获取标准总成本
     * 
     * @return 标准总成本
     */
    public String getCstdcost() {
        return this.cstdcost;
    }

    /**
     * 设置标准总成本
     * 
     * @param cstdcost
     *          标准总成本
     */
    public void setCstdcost(String cstdcost) {
        this.cstdcost = cstdcost;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}