/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.1.0
 */
package com.example.erp.wenwei.pojo;
public class IntotypeEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7518908625670784098L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private String bilno2;

    private Integer typeno;

    private String typeName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取bilno2
     * 
     * @return bilno2
     */
    public String getBilno2() {
        return this.bilno2;
    }

    /**
     * 设置bilno2
     * 
     * @param bilno2
     */
    public void setBilno2(String bilno2) {
        this.bilno2 = bilno2;
    }

    /**
     * 获取typeno
     * 
     * @return typeno
     */
    public Integer getTypeno() {
        return this.typeno;
    }

    /**
     * 设置typeno
     * 
     * @param typeno
     */
    public void setTypeno(Integer typeno) {
        this.typeno = typeno;
    }

    /**
     * 获取typeName
     * 
     * @return typeName
     */
    public String getTypeName() {
        return this.typeName;
    }

    /**
     * 设置typeName
     * 
     * @param typeName
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}