package com.example.erp.wenwei.pojo;
public class IntodetailEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4521910567255710912L;

    /* This code was generated by TableGo tools, mark 1 begin. */


    private String bilno2;


    private String prodid;

  
    private String reason;

    private Integer number;

    private String intodetailno;

   
    private String intobillno;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取bilno2
     * 
     * @return bilno2
     */
    public String getBilno2() {
        return this.bilno2;
    }

    /**
     * 设置bilno2
     * 
     * @param bilno2
     */
    public void setBilno2(String bilno2) {
        this.bilno2 = bilno2;
    }

    /**
     * 获取prodid
     * 
     * @return prodid
     */
    public String getProdid() {
        return this.prodid;
    }

    /**
     * 设置prodid
     * 
     * @param prodid
     */
    public void setProdid(String prodid) {
        this.prodid = prodid;
    }

    /**
     * 获取reason
     * 
     * @return reason
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * 设置reason
     * 
     * @param reason
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * 获取number
     * 
     * @return number
     */
    public Integer getNumber() {
        return this.number;
    }

    /**
     * 设置number
     * 
     * @param number
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * 获取intodetailno
     * 
     * @return intodetailno
     */
    public String getIntodetailno() {
        return this.intodetailno;
    }

    /**
     * 设置intodetailno
     * 
     * @param intodetailno
     */
    public void setIntodetailno(String intodetailno) {
        this.intodetailno = intodetailno;
    }

    /**
     * 获取intobillno
     * 
     * @return intobillno
     */
    public String getIntobillno() {
        return this.intobillno;
    }

    /**
     * 设置intobillno
     * 
     * @param intobillno
     */
    public void setIntobillno(String intobillno) {
        this.intobillno = intobillno;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}