package com.example.erp.wenwei.pojo;
public class MovedetailEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -8102010438031498134L;

    /* This code was generated by TableGo tools, mark 1 begin. */

<<<<<<< HEAD

    private String moveno;

    private String prodid;

    private String reason;

    private String movedetailno;

=======

    private String moveno;

    private String prodid;

    private String reason;

    private String movedetailno;

>>>>>>> parent of feee0d9... s
    private String movebillno;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取moveno
     * 
     * @return moveno
     */
    public String getMoveno() {
        return this.moveno;
    }

    /**
     * 设置moveno
     * 
     * @param moveno
     */
    public void setMoveno(String moveno) {
        this.moveno = moveno;
    }

    /**
     * 获取prodid
     * 
     * @return prodid
     */
    public String getProdid() {
        return this.prodid;
    }

    /**
     * 设置prodid
     * 
     * @param prodid
     */
    public void setProdid(String prodid) {
        this.prodid = prodid;
    }

    /**
     * 获取reason
     * 
     * @return reason
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * 设置reason
     * 
     * @param reason
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * 获取movedetailno
     * 
     * @return movedetailno
     */
    public String getMovedetailno() {
        return this.movedetailno;
    }

    /**
     * 设置movedetailno
     * 
     * @param movedetailno
     */
    public void setMovedetailno(String movedetailno) {
        this.movedetailno = movedetailno;
    }

    /**
     * 获取movebillno
     * 
     * @return movebillno
     */
    public String getMovebillno() {
        return this.movebillno;
    }

    /**
     * 设置movebillno
     * 
     * @param movebillno
     */
    public void setMovebillno(String movebillno) {
        this.movebillno = movebillno;
    }

	@Override
	public String toString() {
		return "MovedetailEntity [moveno=" + moveno + ", prodid=" + prodid + ", reason=" + reason + ", movedetailno="
				+ movedetailno + ", movebillno=" + movebillno + "]";
	}

	public MovedetailEntity(String moveno, String prodid, String reason, String movedetailno, String movebillno) {
		super();
		this.moveno = moveno;
		this.prodid = prodid;
		this.reason = reason;
		this.movedetailno = movedetailno;
		this.movebillno = movebillno;
	}
    
    
    /* This code was generated by TableGo tools, mark 2 end. */
}