package com.example.erp.wenwei.pojo;
public class Movedetail2Entity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5082867176725429298L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private String bilno;

    private String prodid;

    private String reason;

    private Integer number;

    private String outbillno;

    private String outdetailno;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取bilno
     * 
     * @return bilno
     */
    public String getBilno() {
        return this.bilno;
    }

    /**
     * 设置bilno
     * 
     * @param bilno
     */
    public void setBilno(String bilno) {
        this.bilno = bilno;
    }

    /**
     * 获取prodid
     * 
     * @return prodid
     */
    public String getProdid() {
        return this.prodid;
    }

    /**
     * 设置prodid
     * 
     * @param prodid
     */
    public void setProdid(String prodid) {
        this.prodid = prodid;
    }

    /**
     * 获取reason
     * 
     * @return reason
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * 设置reason
     * 
     * @param reason
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * 获取number
     * 
     * @return number
     */
    public Integer getNumber() {
        return this.number;
    }

    /**
     * 设置number
     * 
     * @param number
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * 获取outbillno
     * 
     * @return outbillno
     */
    public String getOutbillno() {
        return this.outbillno;
    }

    /**
     * 设置outbillno
     * 
     * @param outbillno
     */
    public void setOutbillno(String outbillno) {
        this.outbillno = outbillno;
    }

    /**
     * 获取outdetailno
     * 
     * @return outdetailno
     */
    public String getOutdetailno() {
        return this.outdetailno;
    }

    /**
     * 设置outdetailno
     * 
     * @param outdetailno
     */
    public void setOutdetailno(String outdetailno) {
        this.outdetailno = outdetailno;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}