package com.example.erp.wenwei.pojo;
public class OuttpyeEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3175263069984786453L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private String bilno;


    private Integer typeno;


    private String typeName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取bilno
     * 
     * @return bilno
     */
    public String getBilno() {
        return this.bilno;
    }

    /**
     * 设置bilno
     * 
     * @param bilno
     */
    public void setBilno(String bilno) {
        this.bilno = bilno;
    }

    /**
     * 获取typeno
     * 
     * @return typeno
     */
    public Integer getTypeno() {
        return this.typeno;
    }

    /**
     * 设置typeno
     * 
     * @param typeno
     */
    public void setTypeno(Integer typeno) {
        this.typeno = typeno;
    }

    /**
     * 获取typeName
     * 
     * @return typeName
     */
    public String getTypeName() {
        return this.typeName;
    }

    /**
     * 设置typeName
     * 
     * @param typeName
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}