<<<<<<< HEAD

package com.example.erp.wenwei.pojo;

import java.util.Date;

=======

package com.example.erp.wenwei.pojo;

import java.util.Date;

>>>>>>> parent of feee0d9... s
public class OutwareEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1429697172965945421L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** permitter */
    private Integer permitter;

    /** moveDate */
    private Date moveDate;

    /** bilno */
    private String bilno;

    /** makerid */
    private Integer makerid;

    /** voucherno */
    private String voucherno;

    /** outTypeNo */
    private Integer outTypeNo;

    /** outwareno */
    private Integer outwareno;

    /** outemp */
    private Integer outemp;

    /** departid */
    private Integer departid;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取permitter
     * 
     * @return permitter
     */
    public Integer getPermitter() {
        return this.permitter;
    }

    /**
     * 设置permitter
     * 
     * @param permitter
     */
    public void setPermitter(Integer permitter) {
        this.permitter = permitter;
    }

    /**
     * 获取moveDate
     * 
     * @return moveDate
     */
    public Date getMoveDate() {
        return this.moveDate;
    }

    /**
     * 设置moveDate
     * 
     * @param moveDate
     */
    public void setMoveDate(Date moveDate) {
        this.moveDate = moveDate;
    }

    /**
     * 获取bilno
     * 
     * @return bilno
     */
    public String getBilno() {
        return this.bilno;
    }

    /**
     * 设置bilno
     * 
     * @param bilno
     */
    public void setBilno(String bilno) {
        this.bilno = bilno;
    }

    /**
     * 获取makerid
     * 
     * @return makerid
     */
    public Integer getMakerid() {
        return this.makerid;
    }

    /**
     * 设置makerid
     * 
     * @param makerid
     */
    public void setMakerid(Integer makerid) {
        this.makerid = makerid;
    }

    /**
     * 获取voucherno
     * 
     * @return voucherno
     */
    public String getVoucherno() {
        return this.voucherno;
    }

    /**
     * 设置voucherno
     * 
     * @param voucherno
     */
    public void setVoucherno(String voucherno) {
        this.voucherno = voucherno;
    }

    /**
     * 获取outTypeNo
     * 
     * @return outTypeNo
     */
    public Integer getOutTypeNo() {
        return this.outTypeNo;
    }

    /**
     * 设置outTypeNo
     * 
     * @param outTypeNo
     */
    public void setOutTypeNo(Integer outTypeNo) {
        this.outTypeNo = outTypeNo;
    }

    /**
     * 获取outwareno
     * 
     * @return outwareno
     */
    public Integer getOutwareno() {
        return this.outwareno;
    }

    /**
     * 设置outwareno
     * 
     * @param outwareno
     */
    public void setOutwareno(Integer outwareno) {
        this.outwareno = outwareno;
    }

    /**
     * 获取outemp
     * 
     * @return outemp
     */
    public Integer getOutemp() {
        return this.outemp;
    }

    /**
     * 设置outemp
     * 
     * @param outemp
     */
    public void setOutemp(Integer outemp) {
        this.outemp = outemp;
    }

    /**
     * 获取departid
     * 
     * @return departid
     */
    public Integer getDepartid() {
        return this.departid;
    }

    /**
     * 设置departid
     * 
     * @param departid
     */
    public void setDepartid(Integer departid) {
        this.departid = departid;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}