package com.example.erp.wenwei.pojo;
public class WaredetailEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -8785974792145885889L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private String checkbillno;


    private String waredetailno;


    private String prodid;


    private Integer saleNumber;

    private String reason;

    private String checkBill;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取checkbillno
     * 
     * @return checkbillno
     */
    public String getCheckbillno() {
        return this.checkbillno;
    }

    /**
     * 设置checkbillno
     * 
     * @param checkbillno
     */
    public void setCheckbillno(String checkbillno) {
        this.checkbillno = checkbillno;
    }

    /**
     * 获取waredetailno
     * 
     * @return waredetailno
     */
    public String getWaredetailno() {
        return this.waredetailno;
    }

    /**
     * 设置waredetailno
     * 
     * @param waredetailno
     */
    public void setWaredetailno(String waredetailno) {
        this.waredetailno = waredetailno;
    }

    /**
     * 获取prodid
     * 
     * @return prodid
     */
    public String getProdid() {
        return this.prodid;
    }

    /**
     * 设置prodid
     * 
     * @param prodid
     */
    public void setProdid(String prodid) {
        this.prodid = prodid;
    }

    /**
     * 获取saleNumber
     * 
     * @return saleNumber
     */
    public Integer getSaleNumber() {
        return this.saleNumber;
    }

    /**
     * 设置saleNumber
     * 
     * @param saleNumber
     */
    public void setSaleNumber(Integer saleNumber) {
        this.saleNumber = saleNumber;
    }

    /**
     * 获取reason
     * 
     * @return reason
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * 设置reason
     * 
     * @param reason
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * 获取checkBill
     * 
     * @return checkBill
     */
    public String getCheckBill() {
        return this.checkBill;
    }

    /**
     * 设置checkBill
     * 
     * @param checkBill
     */
    public void setCheckBill(String checkBill) {
        this.checkBill = checkBill;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}